### PR TITLE
feat: add ability to select layout

### PR DESCRIPTION
**Pull request by christojeffrey**

### CODE REVIEW

**Review by Perry26 — APPROVED** [review]
lgtm.

**Comment by christojeffrey** [comment]
need to update based on new layout

**Comment by Perry26** [comment]
Do you mean you want to add a toggle for wheater there is edge routing? I don't see any new layout missing (though you did forget about the force-based layout)

**Comment by Perry26** [comment]
See PR #47

**Comment by Perry26** [comment]
I merged main into this so we can show it in an hour. I'd like to merge this into main soonish becaue it's usefull for demo's.

**Comment by christojeffrey** [comment]
Adit is going to take over this. It should be good enough, can you test @Adityapnn811 ?

**Comment by Adityapnn811** [comment]
> Adit is going to take over this. It should be good enough, can you test @Adityapnn811 ?

I've tested it, it is working

**Review by Adityapnn811 — APPROVED** [review]

**Pull request merged**
