### PR TITLE
Feat/tree layout edge routing

### PR DESCRIPTION
**Pull request by Perry26**
Since the layer-tree layout computes edge-routing information as a side-effect anyway, it would be a shame not to use it.

Unfortunatly, we'd need to find a better way to handle curved edges for this to really be usefull. Right now I try to approximate an order-n Berziercurve using only quadratic polyberziercurves but it doesn't really work sometimes, creating weird edges which seem to "bounce around" (make 180 degree turns). 

I think it may be wise to already have this infrastructure in place. I'd consider the rendering issue something we could look into later

### CODE REVIEW

**Comment by christojeffrey** [comment]
is this PR ready for review?

**Comment by Perry26** [comment]
In general, I won't make a pr unless its ready for review @christojeffrey

**Comment by christojeffrey** [comment]
> In general, I won't make a pr unless its ready for review @christojeffrey

okay thanks for your confirmation!

can we wait for these PR first? #33 #36

**Comment by christojeffrey** [comment]
when is an edge gonna be curved?

**Comment by Perry26** [comment]
It's going to be curved if an edge had "routing points" in its rendering information, which are just coordinates it needs to pass through.

The tree layout generates such points due to the fact that some edges go through "dummy" nodes, which are then converted to routing points.

**Review by christojeffrey — APPROVED** [review]

**Comment by christojeffrey** [comment]
> It's going to be curved if an edge had "routing points" in its rendering information, which are just coordinates it needs to pass through.
> 
> The tree layout generates such points due to the fact that some edges go through "dummy" nodes, which are then converted to routing points.

I think I am gonna ask this at some point in the future. for now let's share that responsibility to future me haha

**Pull request merged**
