### PR TITLE
feat: UI changes, collapse node, some structural

### PR DESCRIPTION
**Pull request by christojeffrey**
also made some changes on converter. 
reference data: 
image

converted data result:
image

not yet rigorously tested (for example with data inside data inside data inside)

### CODE REVIEW

**Comment by christojeffrey** [comment]
changes:
1. seperating create graphData with filter. Now filter doesn't necessarily recreate the graphData. why? cause everytime the graphData is changed, the whole svg is recreated which 'flicker' the screen. bad UX. 
2. rethinking config. previously, everytime config is changed - graphData is changed. here's the reasoning

# what to do when config is changed?
## option 1: recreate graphData from convertedData. 

if we recreate graphData every time config is changed, it will, like flash everytime. it will recreate the whole thing from zero. each time. the node will go back to their original place.
[Screencast from 2024-01-24 16-02-13.webm](https://github.com/christojeffrey/software-visualization/assets/71057204/ba8f0d6c-002a-4470-b70f-13f5192ad66e)


## option 2. have 2 graphData. one is pure, one is changed based on config.
why not create 2 graphData? one is full, one is ... with missing stuff based on config. 

but how?
for example, we have linkA. from node1 to node2.

and inside the filteredGraphData, it is redirected from node1 to node3.
 if we change the second graphData, the first one will be changed too. 

## option 3. don't modify graphData till it's unrecoverable. always keep it recoverable. 
we can modify by adding new attribute. such as 'hidden' to collapseVertices. 

---
3. update the UI looks nicer now. tailwind is added. 
4. adding `originalTarget` , `originalSource`, `originalMembers`, `incomingLinks`, `outgoingLinks` as reference. First 3 is the effect of taking the option 3 in the explanation above. last 2 is to make computation easier, making it really easy to add feature: highlight on hover! (kinda cool i think)

---
side note:
the filter feels weird now. As the filtering itself actually doesn't really need to be done inside the filter function. but no alternatives pop in my mind yet. 

---
next:
need to update naming. still incosistent use of the word 'node' and 'vertex'

**Comment by christojeffrey** [comment]
image
the UI now

**Comment by christojeffrey** [comment]
5. moving the route to /v1 and /v2

**Comment by Adityapnn811** [comment]
> changes:
> 
>     1. seperating create graphData with filter. Now filter doesn't necessarily recreate the graphData. why? cause everytime the graphData is changed, the whole svg is recreated which 'flicker' the screen. bad UX.
> 
>     2. rethinking config. previously, everytime config is changed - graphData is changed. here's the reasoning
> 
> 
> # what to do when config is changed?
> ## option 1: recreate graphData from convertedData.
> 
> if we recreate graphData every time config is changed, it will, like flash everytime. it will recreate the whole thing from zero. each time. the node will go back to their original place. [Screencast from 2024-01-24 16-02-13.webm](https://github.com/christojeffrey/software-visualization/assets/71057204/ba8f0d6c-002a-4470-b70f-13f5192ad66e)
> ## option 2. have 2 graphData. one is pure, one is changed based on config.
> 
> why not create 2 graphData? one is full, one is ... with missing stuff based on config.
> 
> but how? for example, we have linkA. from node1 to node2.
> 
> and inside the filteredGraphData, it is redirected from node1 to node3. if we change the second graphData, the first one will be changed too.
> ## option 3. don't modify graphData till it's unrecoverable. always keep it recoverable.
> 
> we can modify by adding new attribute. such as 'hidden' to collapseVertices.
> 
>     3. update the UI looks nicer now. tailwind is added.
> 
>     4. adding `originalTarget` , `originalSource`, `originalMembers`, `incomingLinks`, `outgoingLinks` as reference. First 3 is the effect of taking the option 3 in the explanation above. last 2 is to make computation easier, making it really easy to add feature: highlight on hover! (kinda cool i think)
> 
> 
> side note: the filter feels weird now. As the filtering itself actually doesn't really need to be done inside the filter function. but no alternatives pop in my mind yet.
> 
> next: need to update naming. still incosistent use of the word 'node' and 'vertex'

I think we can utilize the enter, update, and exit function from d3. Still a rough idea tho. Here is the reference https://www.d3indepth.com/enterexit/

**Comment by Adityapnn811** [comment]
Anyway, this is a lot so it's gonna take some time from me, might test few of the changes too

**Comment by Perry26** [comment]
> changes:
> 
> 1. seperating create graphData with filter. Now filter doesn't necessarily recreate the graphData. why? cause everytime the graphData is changed, the whole svg is recreated which 'flicker' the screen. bad UX.
> 2. rethinking config. previously, everytime config is changed - graphData is changed. here's the reasoning
> 
> # what to do when config is changed?
> ## option 1: recreate graphData from convertedData.
> if we recreate graphData every time config is changed, it will, like flash everytime. it will recreate the whole thing from zero. each time. the node will go back to their original place. [Screencast from 2024-01-24 16-02-13.webm](https://github.com/christojeffrey/software-visualization/assets/71057204/ba8f0d6c-002a-4470-b70f-13f5192ad66e)
> 
> ## option 2. have 2 graphData. one is pure, one is changed based on config.
> why not create 2 graphData? one is full, one is ... with missing stuff based on config.
> 
> but how? for example, we have linkA. from node1 to node2.
> 
> and inside the filteredGraphData, it is redirected from node1 to node3. if we change the second graphData, the first one will be changed too.
> 
> ## option 3. don't modify graphData till it's unrecoverable. always keep it recoverable.
> we can modify by adding new attribute. such as 'hidden' to collapseVertices.
> 
> 3. update the UI looks nicer now. tailwind is added.
> 4. adding `originalTarget` , `originalSource`, `originalMembers`, `incomingLinks`, `outgoingLinks` as reference. First 3 is the effect of taking the option 3 in the explanation above. last 2 is to make computation easier, making it really easy to add feature: highlight on hover! (kinda cool i think)
> 
> side note: the filter feels weird now. As the filtering itself actually doesn't really need to be done inside the filter function. but no alternatives pop in my mind yet.
> 
> next: need to update naming. still incosistent use of the word 'node' and 'vertex'

Might want to discuss this in more detail Friday, but yeah I would say that using enter and exit is the best solution probably (that's the main point of d3). 

I think having an immutable datastructure behind the graphData is unavoidable, simply because we have to create and remove edges for the collapsing and dependency lifting. We can either do that as mentioned in option 2 + enter/exit function (A sensible scheme for nodeid's is vital for this), or we can augment the convertedData somehow (would me more memory efficient, but also somewhat messy)

**Comment by Perry26** [comment]
```
+	const nodes: any = JSON.parse(JSON.stringify(convertedData.nodes));
+	const links: any = JSON.parse(JSON.stringify(convertedData.links));
+	console.log(nodes);
+	console.log(links);
```
I have no idea what the JSON.stringify/JSON.parse is doing here, but I think this is going to cause issues sooner or later. (Also, please remove console.log statements before submitting a pull request)

Also, did you just remove all the dependency lifting stuff I implemented in the other PR?

**Comment by christojeffrey** [comment]
its to copy do deep copy of the whole object. it's a relatively common way to do it. but yeah I kinda not sure how it handles the edgeType. 
I think I tried Object copy but doesn't work the way I imagine it to. 

and nope, I think your PR is still here. I create this inside a new route called /v2, yours is in /test so it should be good. But I think it's still going to be like a breaking changes. we're moving relatively fast here, so yeah there's gonna be alot of mismatch that needs to be ironed out. I am merging yours locally (like manually pick and choose the code), but I think we can still merge this one first.

**Comment by christojeffrey** [comment]
btw I actually went option 3 in implementing it. you try to run it locally to get a better idea. But yeah if it's actually better to use update enter exit, I am open to it. though right now I have no idea how to use them for this

**Comment by christojeffrey** [comment]
I've put lifting inside v2 route. tested it a bit using simple hard coded config. should be conflict free now. still need to do lots of tidying up, but let's do it after this PR before it gets bigger and bigger

**Review by Adityapnn811 — APPROVED** [review]
The logic looks fine, not sure if it's the most efficient way because there's a lot of brute force searching due to the nodes being an object currently. The current bug I find are the force simulation stopping and the collapse button not 'attached'.

**Review by Perry26 — APPROVED** [review]
Then I'll approve this. I'll make a seperate PR to connect the linking stuff to the UI.

**Comment by christojeffrey** [comment]
> The logic looks fine, not sure if it's the most efficient way because there's a lot of brute force searching due to the nodes being an object currently. The current bug I find are the force simulation stopping and the collapse button not 'attached'.

okay. i'll handle this on another PR

**Pull request merged**
