### PR TITLE
prettier fix

### PR DESCRIPTION
**Pull request by christojeffrey**
I wasn't aware that there's an existing .prettierrc in our project. this [PR](https://github.com/christojeffrey/software-visualization/pull/34) was used to add that prettierrc but since there's one already, I am closing it. This PR is the follow up, where I run `npx prettier --write "./**/*.{js,jsx,ts,tsx,svelte}"`

### CODE REVIEW

**Comment by christojeffrey** [comment]
I added `lint:fix` in the package.json also if you prefer to use it rather than formatting on save on vscode

**Comment by Perry26** [comment]
If we do this, can we please set trailingComma to all or at least es5 instead of none? It works a lot better in combination with git.

**Comment by Perry26** [comment]
Some stuff I'm less opinionated about but I think is easier to read:
arrowParens: "avoid"
bracketSpacing: "false"

(I think prettier has the annoying property to make files unnececaraly large, so I like the options which are more compact) Otherwise I'm fine with this.

**Comment by christojeffrey** [comment]
sure! whatever easier for you

**Review by Perry26 — APPROVED** [review]
Fixed it

**Comment by christojeffrey** [comment]
nice!

**Comment by christojeffrey** [comment]
it's conflicting with main. I'll manually pick the changes and run lint:fix again

**Pull request merged**
