### PR TITLE
Implement layer-tree layout

### PR DESCRIPTION
**Pull request by Perry26**
Implements a layered tree layout.

Will still augment this to do some edge routing, but let's first merge the actual node-layout

### CODE REVIEW

**Review by Adityapnn811 — COMMENTED** [review]
From what I've seen and tried it's working fine. Although, I'm gonna be honest I'm not entirely sure what to expect from the layeredTree result. Can you explain a little bit about how it decides the layer a node belongs to? Also, I noticed some gaps in each layer, is it caused by the dummyNode?

**Comment by Perry26** [comment]
The gaps are there by design. There should be where there's a lot of edges going from the  previous layer to the next layer. There's currently no edgerouting (yet), so it's not ideal, but that would be a great spot to send edges through.

The algorithm basically discovers a DAG by 'removing' (meaning ignoring) cycles, and then assigns layers by topoligically sorting the nodes. This means on the first layer, all nodes with no incoming edges are placed. On the next layer, all nodes with incoming edges from the previous layer are places, etc... (This still leaves the "gaps'/dummynodes because we discover a DAG, not a tree). 

Finally, nodes in a layer are ordered such that it is in the median position of its "predesessors" (nodes in previous layer it is connected to) via a heuristic.

**Comment by Perry26** [comment]
... Is that explanation clear or do you want more @Adityapnn811

**Comment by Adityapnn811** [comment]
Ah okay, it's clear enough. Thanks. I'll approve the PR

**Review by Adityapnn811 — APPROVED** [review]

**Pull request merged**
