### PR TITLE
Implement rectangle collision force

### PR DESCRIPTION
**Pull request by Perry26**
First required for properly layouting our nodes with big nested data. 

It results in a lot of jitter, unfortunatly, I think that is partially caused by other forces being to strict.

(And yes, I know this is computationally a bit intensive, however remember that the simlation doesn't contain all nodes, so it should be fine.)

### CODE REVIEW

**Comment by christojeffrey** [comment]
nice, I like the idea of this force

is this the expected behavior?

[Screencast from 2024-01-30 23-24-29.webm](https://github.com/christojeffrey/software-visualization/assets/71057204/0edc0db4-c9eb-4c1d-9c9e-76da1ee97753)

**Comment by christojeffrey** [comment]
also this one

[Screencast from 2024-01-30 23-28-08.webm](https://github.com/christojeffrey/software-visualization/assets/71057204/e9300712-8e63-4ae0-8499-280836a365c5)

**Comment by Perry26** [comment]
Expansion should push the nodes out of eachother yeah. 

It sometimes bugs out due to not all simulations being active. That collision detection bug in video 1 should probably be fixed though.

(For the record, node.width and node.height as set in the mastersimulationticked are supposed to reliably contain the exact drawing height and width, right?)

**Comment by christojeffrey** [comment]
to me, those two videos show quite a few unwanted behaviors.


I think yes for the width and height. though the location of the node is not exactly the same place as what is shown on the screen. check the implementation of tick or draw I think. 

I think you should know, 
there are two moving components, svg container g, and the node. 

if you think that this is not ideal (why not just only move one of them?), I would agree. But I can't make the behavior as smooth as right now, with just moving one of them.

**Comment by Perry26** [comment]
I think this fixes most bugs. The simulation restarting thing is still a bit annoying though, but we'll have to think about that later

**Pull request closed without merging**
