### PR TITLE
[feat] draw settings components and link and node labels. more things configurable now. also do some fixing

### PR DESCRIPTION
**Pull request by christojeffrey**

### CODE REVIEW

**Comment by christojeffrey** [comment]
check the commit title for more information

**Comment by christojeffrey** [comment]
this handle tasks below

image

**Review by Perry26 — APPROVED** [review]

**Comment by Adityapnn811** [comment]
I will resolve the conflict

EDIT: @christojeffrey I've resolved it

**Comment by christojeffrey** [comment]
alright thank you dit

**Pull request merged**
