### PR TITLE
feat: able to lift and collapse on button click

### PR DESCRIPTION
**Pull request by christojeffrey**

### CODE REVIEW

**Comment by christojeffrey** [comment]
to help reviewing: in draw.ts, I add more stuff inside rerender function. and remove the function that's called outside of rerender (because it's always gonna be called by doRedraw)

**Comment by Perry26** [comment]
I'm sorry, I find it hard to find your changes inbetween all the stuff prettier introduced. (Please always make sure everyone agrees on using it before turning on such a tool).

The main change of the code is this piece, right? 
```		redirectDestination.members?.forEach((member) => {
			redirectAllEdgeToDestinationNode(redirectDestination, member);
		});
```
And the fact that you use rerender for the initial render, rather then strictly rerendering stuff.

**Comment by christojeffrey** [comment]
> I'm sorry, I find it hard to find your changes inbetween all the stuff prettier introduced. (Please always make sure everyone agrees on using it before turning on such a tool).
> 
> The main change of the code is this piece, right?
> 
> ```
> 			redirectAllEdgeToDestinationNode(redirectDestination, member);
> 		});
> ```
> 
> And the fact that you use rerender for the initial render, rather then strictly rerendering stuff.

if I am understanding you correctly, yep you're right. To be safe, we can run add prettier config and fix all of it (npx prettier .) to reduce prettier changes. 
sorry I didn't confirm first, I assume everyone uses them. Do you use them?

**Review by Perry26 — APPROVED** [review]
In that case this is fine, especially since we're fixing the linter stuff in the other PR.

I usually dislike prettier and typically work without a linter and just format my code myself. But I don't mind a linter as long as we're clear on what we're using.

**Pull request merged**
